version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      storybook:
        patterns:
          - ^@storybook/.*
          - ^storybook$
    open-pull-requests-limit: 99
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 99
